#!/bin/bash

cc="ccache gcc"
output_dir=build_allmodconfig_warn/
ncpu=$(grep -c processor /proc/cpuinfo)
build_flags="-Oline -j $ncpu W=1 C=1"
tmpfile_o=$(mktemp)
tmpfile_n=$(mktemp)
rc=0

echo "Using $build_flags redirect to $tmpfile_o and $tmpfile_n"
echo "CC=$cc"
$cc --version | head -n1

BRANCH=$(git rev-parse --abbrev-ref HEAD)
HEAD=$(git rev-parse $1)
PARENT=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})

echo $HEAD
echo $PARENT

git checkout -q $PARENT

echo "Building the tree before the patch"

prep_config
make CC="$cc" O=$output_dir $build_flags 2> >(tee $tmpfile_o >&2)
incumbent=$(grep -i -c "\(warn\|error\)" $tmpfile_o)

echo "Building the tree with the patch"

git checkout -q $HEAD

# Also force rebuild "after" in case the file added isn't important.
if ! git log --diff-filter=A $PARENT.. --exit-code >>/dev/null; then
    touch ${output_dir}/include/generated/utsrelease.h
fi

prep_config
make CC="$cc" O=$output_dir $build_flags 2> >(tee $tmpfile_n >&2) || rc=1

current=$(grep -i -c "\(warn\|error\)" $tmpfile_n)

echo "Errors and warnings before: $incumbent this patch: $current"

if [ $current -gt $incumbent ]; then
  echo "New errors added" 1>&2
  diff -U 0 $tmpfile_o $tmpfile_n 1>&2

  echo "Per-file breakdown" 1>&2
  tmpfile_fo=$(mktemp)
  tmpfile_fn=$(mktemp)

  grep -i "\(warn\|error\)" $tmpfile_o | sed -n 's@\(^\.\./[/a-zA-Z0-9_.-]*.[ch]\):.*@\1@p' | sort | uniq -c \
    > $tmpfile_fo
  grep -i "\(warn\|error\)" $tmpfile_n | sed -n 's@\(^\.\./[/a-zA-Z0-9_.-]*.[ch]\):.*@\1@p' | sort | uniq -c \
    > $tmpfile_fn

  diff -U 0 $tmpfile_fo $tmpfile_fn 1>&2
  rm $tmpfile_fo $tmpfile_fn

  rc=1
else
  echo "no new warnings added"
fi

git checkout $BRANCH

rm $tmpfile_o $tmpfile_n

exit $rc
