#!/bin/sh
# Need to do all these:
# touch $file && make C=2 $file
# touch $file && make C=2 CHECK="scripts/coccicheck"
# KASAN, KMSAN, KCSAN
# ./scripts/kernel-doc -none $file
# smatch:
# https://rajanvaja.wordpress.com/2021/02/06/how-to-run-smatch-on-linux-kernel/

set -ex

source ~/bin/create-patches

files=""
create_patches $@

# checkpatch
set +e
for file in $files; do
	if cat $file | grep -q "not-for-review\|only-internal-review"; then
		continue;
	fi
	sed '/Change-Id:/d' $file -i
	./scripts/checkpatch.pl --patch $file --codespell
done
set -e

# open files for manual review
for file in $files; do
	if cat $file | grep -q "not-for-review\|only-internal-review"; then
		continue;
	fi
	vim $file
done

# kernel-doc
files=$(git diff "$RANGE" --name-only)
echo kernel-doc...
for file in $files; do
	./scripts/kernel-doc -none $file
done
echo done kernel-doc

<<FUB
# Extra checks I can't figure out to work yet.
echo coccicheck...
files=$(git diff "$RANGE" --name-only)
o_files=()
for file in $files; do
	if [[ $file != *testing* ]]; then
		if [[ $file == *.c ]]; then
			o_file="${file%.c}.o"
			o_files+=($o_file)
		fi

	fi
done
echo ${o_files[*]}

sudo make -s -j80 C=2 ${o_files[*]}

echo smatch...
sudo ~/smatch/smatch_scripts/build_kernel_data.sh
sudo ~/smatch/smatch_scripts/test_kernel.sh
echo done smatch
FUB
