#!/bin/sh
# Need to do all these:
# touch $file && make C=2 $file
# touch $file && make C=2 CHECK="scripts/coccicheck"
# KASAN, KMSAN, KCSAN
# ./scripts/kernel-doc -none $file
# smatch:
# https://rajanvaja.wordpress.com/2021/02/06/how-to-run-smatch-on-linux-kernel/

set -ex

source ~/bin/create-patches

files=""
create_patches $@

# checkpatch
set +e
for file in $files; do
	if cat $file | grep -q "not-for-review\|only-internal-review"; then
		continue;
	fi
	sed '/Change-Id:/d' $file -i
	./scripts/checkpatch.pl --patch $file --codespell
done
set -e

# kernel-doc
files=$(git diff "$RANGE" --name-only)
echo kernel-doc...
for file in $files; do
	./scripts/kernel-doc -none $file
done
echo done kernel-doc
