#! /bin/sh
#
#
set -ex

alias staging_gcloud='/google/data/ro/teams/cloud-sdk/gcloud'

instance1=$1
instance2=$2

random_port=$((RANDOM%100+5201))
echo $random_port

if [ ! -z $3 ]; then
  staging_gcloud compute scp $3 $instance1:~/
  staging_gcloud compute scp $3 $instance2:~/
fi

CLIENT=$(staging_gcloud compute ssh $instance2 -- "ifconfig | grep -i 'inet 192.168.1.'" | awk '{print $2}')
SERVER=$(staging_gcloud compute ssh $instance1 -- "ifconfig | grep -i 'inet 192.168.1.'" | awk '{print $2}')

sed -i "s/SERVER/$SERVER/g" ~/bin/server
sed -i "s/CLIENT/$CLIENT/g" ~/bin/server
sed -i "s/SERVER/$SERVER/g" ~/bin/client
sed -i "s/CLIENT/$CLIENT/g" ~/bin/client
set +e
sed -i "s/SERVER/$SERVER/g" scripts/queue-api-client
sed -i "s/CLIENT/$CLIENT/g" scripts/queue-api-client
sed -i "s/SERVER/$SERVER/g" scripts/queue-api-server
sed -i "s/CLIENT/$CLIENT/g" scripts/queue-api-server
set -e

staging_gcloud compute scp ~/bin/server $instance1:~/
staging_gcloud compute scp ~/bin/client $instance2:~/
set +e
staging_gcloud compute scp scripts/queue-api-server $instance1:~/
staging_gcloud compute scp scripts/queue-api-client $instance2:~/
set -e

staging_gcloud compute scp ~/neper/tcp_stream $instance1:~/
staging_gcloud compute scp ~/neper/tcp_stream $instance2:~/

sed -i "s/$SERVER/SERVER/g" ~/bin/server
sed -i "s/$CLIENT/CLIENT/g" ~/bin/server
sed -i "s/$SERVER/SERVER/g" ~/bin/client
sed -i "s/$CLIENT/CLIENT/g" ~/bin/client
set +e
sed -i "s/$SERVER/SERVER/g" scripts/queue-api-client
sed -i "s/$CLIENT/CLIENT/g" scripts/queue-api-client
sed -i "s/$SERVER/SERVER/g" scripts/queue-api-server
sed -i "s/$CLIENT/CLIENT/g" scripts/queue-api-server
set -e

staging_gcloud compute ssh $instance1 -- \
  "sudo mount -o remount,exec /home && \
   sudo iptables -I INPUT -p tcp -m tcp -j ACCEPT && \
   sudo ethtool -K eth1 ntuple on || true && \
   sudo ethtool --set-priv-flags eth1 enable-header-split on && \
   sudo ethtool --set-priv-flags eth1 enable-max-rx-buffer-size on"

staging_gcloud compute ssh $instance2 -- \
  "sudo mount -o remount,exec /home && \
   sudo iptables -I INPUT -p tcp -m tcp -j ACCEPT && \
   sudo ethtool -K eth1 ntuple on || true && \
   sudo ethtool --set-priv-flags eth1 enable-header-split on && \
   sudo ethtool --set-priv-flags eth1 enable-max-rx-buffer-size on"
