#!/bin/sh

set -x

alias staging_gcloud='/google/data/ro/teams/cloud-sdk/gcloud'

VM1=$1
VM2=$2

while ! cos-dev build_gpu $VM1 $VM2; do sleep 5; done

while ! cos-dev deploy_gpu $VM1 $VM2; do sleep 5; done

pushd ~/tcp-devmem-samples
while ! ./scripts/copy-benchmark-cos $VM1 $VM2 2>&1 > /dev/null; do sleep 5; done
popd

while ! ./scripts/run-stable $VM1 $VM2; do sleep 5; done
