#!/bin/sh

command -v hg >/dev/null 2>&1 || {
  echo >&2 "Hg should be available."
  exit 1
}

hg qapplied >/dev/null 2>&1 || {
  echo >&2 "Mq not available"
  exit 1
}

[[ -z `hg qapplied` ]] && {
  echo >&2 "No patches applied"
  exit 1
}

[[ ! -z `hg status` ]] && {
  echo >&2 "You have local changes."
  exit 1
}

if [ $# -ne 1 ];
then
  echo "Need exactly one argument"
  exit 1
fi

hg qnew -m "$1" try || {
  echo >&2 "Failed to create try."
  exit 1
}

hg push -f try || {
  echo >&2 "Failed to push try."
}

hg qpop
hg qremove try
