#!/bin/sh
#
# Workflow:
# git co -b my-branch --track net-next/main
# vim ...
# git a .
# git cm -m "my patch"
#
# # Creates patches under my-branch/
# patches create -v 1
#
# # clang-format each patch in a git rebase --exec
# patches clang_format
#
# # Runs checkpatch
# patches checkpatch
#
# # Runs patch-by-patch W=1 C=1 in a git rebase --exec
# patches build_patch_by_patch
#	# if you run into errors
#	vim ...				# fix the errors
#	git cm --amend			# commit the fixes
#	build_patch_with_checks.sh	# check if the errors still happen
#	git rebase --continue		# Carry on with the patch-by-patch build
#
# # Build patch-by-patch allmodconfig in a git rebase --exec
# patches build_allmodconfig_patch_by_patch
#
# # Run all the checks, and send the patches upstream
# patches presubmit && patches send -v 1

set -euo pipefail
# Turn on for debugging
set -x

TEST="${TEST:-0}"

head=$(git rev-parse --abbrev-ref --symbolic-full-name HEAD)
parent=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
RANGE="${RANGE:-"$parent..HEAD"}"
git_send_to="netdev@vger.kernel.org"

echoerr() { cat <<< "$@" 1>&2; }

function create() {
	rm -rf $head/*.patch

	local cover_letter=""
	set +e
	git config branch.$head.description > .description.txt && \
		cover_letter="1"
	set -e

	count=$(($(git rev-list --count "$RANGE")))

	if [[ $count < 1 ]]; then
		echo "Not enough commits in range: $count"
		exit 1
	fi

	if [[ $count > 1 ]] && [ ! -z "$cover_letter" ]; then
		cover_letter="--cover-letter --cover-from-description=auto --description-file=.description.txt"
	else
		cover_letter=""
	fi

	local to=$(git diff "$RANGE" | ./scripts/get_maintainer.pl \
		--nogit-fallback --norolestats -nom -nor --nomoderated \
		--nomultiline)
	local cc=$(git diff "$RANGE" | ./scripts/get_maintainer.pl \
		--nogit-fallback --norolestats -nol --nomoderated --nomultiline)

	# TODO, this assumes net-next
	local files=$(git format-patch \
		-o $head \
		"$RANGE" \
		$cover_letter \
		--to="$to" \
		--cc="$cc" \
		--subject-prefix='PATCH net-next' \
		"$@")

	# Delete change-id
	for file in $files; do
		sed '/Change-Id:/d' $file -i
	done

	echo $files
}

send() {
	local files=$(create $@)
	CONFIRM=${CONFIRM:-}

	if [[ $TEST == 0 ]]; then
		DRY_RUN=""
	else
		DRY_RUN="--dry-run"
	fi

	if [ ! -z $CONFIRM ]; then
		presubmit
	fi

	yes | git send-email $files --to="$git_send_to" --cc-cover --8bit-encoding=UTF-8 $CONFIRM $DRY_RUN || true

	git tag "$head-$FUNCNAME-$(date +%F-%s)"
}

checkpatch() {
	local files=$(create $@)
	local tmpfile=$(mktemp)

	# checkpatch
	for file in $files; do
		if grep "not-for-review" $file; then
			exit 1
		fi
		set +e
		./scripts/checkpatch.pl --patch $file --codespell | tee $tmpfile
		errors=$(grep -c "ERROR" $tmpfile)
		set -e
		if [ $errors -gt 0 ]; then
			exit $errors
		fi
	done

	rm -rf $tmpfile

	local tmpfile=$(mktemp)

	# kernel-doc
	local touched=$(git diff "$RANGE" --name-only)
	echo kernel-doc...
	for file in $touched; do
		./scripts/kernel-doc -none $file 2>&1 | tee $tmpfile
		set +e
		errors=$(grep -i -c "\(warn\|error\)" $tmpfile)
		set -e
		if [ $errors -gt 0 ]; then
			exit $errors
		fi
	done
	echo done kernel-doc
}

build_allmodconfig_patch_by_patch() {
	local dir=build_allmodconfig/
	make allmodconfig O=$dir
	git rebase --exec \
		"git show | grep -q \"not-for-review\" || make -s -j`nproc` O=$dir" \
		$parent

	echo "Test build patches succeeded"

	git tag "$head-$FUNCNAME-$(date +%F-%s)"
}

build_patch_by_patch() {
	git clean -fdx
	touch .first_in_series

	git rebase --exec \
		'git show | grep -q "not-for-review" || PATCHES_CONFIG=allnoconfig ~/bin/build_patch_with_checks.sh' \
		$parent

	echo "Test build patches succeeded"
	git tag "$head-$FUNCNAME-$(date +%F-%s)"
}

clang_format() {
	git rebase --exec \
		'git show | grep -q "not-for-review" || git diff -U0 --no-color HEAD~ | /usr/lib/clang-format/clang-format-diff.py -i -p1' $parent
}

build_configs() {
	local rc=0
	local dir=allnoconfig/
	for config in $(ls ../$head/*.config); do
		KCONFIG_ALLCONFIG="$config" make allnoconfig -s O=$dir
		make -j`nproc` -s O=$dir || rc=$?
	done

	make allnoconfig -s O=$dir
	make -j`nproc` -s O=$dir || rc=$?

	git tag "$head-$FUNCNAME-$(date +%F-%s)"
	echo $rc
}

presubmit() {
	sudo git clean -fdx

	git fetch net-next # TODO, this assumes net-next

	git rebase

	checkpatch

	local rc=$(build_configs)
	if [[ $rc != 0 ]]; then
		exit $rc
	fi

	build_patch_by_patch

	build_allmodconfig_patch_by_patch
}

send_no_confirm() {
	presubmit

	CONFIRM="--confirm=never" send $@
}

command="$1"
shift

if [ "$command" == "create" ]; then
	create $@
elif [ "$command" == "send" ]; then
	send $@
elif [ "$command" == "send_no_confirm" ]; then
	send_no_confirm $@
elif [ "$command" == "checkpatch" ]; then
	checkpatch $@
elif [ "$command" == "build_patch_by_patch" ]; then
	build_patch_by_patch $@
elif [ "$command" == "build_allmodconfig_patch_by_patch" ]; then
	build_allmodconfig_patch_by_patch $@
elif [ "$command" == "presubmit" ]; then
	presubmit $@
elif [ "$command" == "clang_format" ]; then
	clang_format $@
elif [ "$command" == "build_configs" ]; then
	local rc=$(build_configs $@)
	exit $rc
fi
