#!/bin/sh

#
# Workflow:
# ~/bin/clang-format-patches
# ~/bin/checkpatches
# ~/bin/test-build-patches
# ~/bin/get-maintainers
# ~/bin/send-patches -v $v.

set -ex

source ~/bin/create-patches

head=$(git rev-parse --abbrev-ref --symbolic-full-name HEAD)

files=""
create_patches $@

for file in $files; do
	sed '/Change-Id:/d' $file -i
	vim $file
done

git tag "$head-$(date +%F-%s)"

git send-email \
	$files \
	--cc-cover
