#!/bin/sh

#
# Workflow:
# ~/bin/clang-format-patches
# RANGE="net-next/main..HEAD~22" ~/bin/checkpatch-patches -v 12
#
# ~/bin/build-series-quick HEAD~22
# ~/bin/build-patch-by-patch-quick
#
# ~/bin/build-patch-by-patch
#
# RANGE="net-next/main..HEAD~22" ~/bin/send-patches -v 12

set -ex

source ~/bin/create-patches

head=$(git rev-parse --abbrev-ref --symbolic-full-name HEAD)

files=""
create_patches $@

for file in $files; do
	sed '/Change-Id:/d' $file -i
	vim $file
done

git tag "$head-$(basename "$0")-$(date +%F-%s)"

git send-email \
	$files \
	--cc-cover
