#!/bin/sh

set -e

rm -rf before-build-errors.txt
rm -rf after-build-errors.txt

head=$(git rev-parse --abbrev-ref --symbolic-full-name HEAD)
parent=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})

git co $parent
echo hero
sudo make clean
echo hero
sudo KCONFIG_ALLCONFIG=../devmem.config make allnoconfig
sudo make -j80 C=1 2>before-build-errors.txt
echo hero

git co $head
sudo make clean
sudo KCONFIG_ALLCONFIG=../devmem.config make allnoconfig
sudo make -j80 C=1 2>after-build-errors.txt

diff before-build-errors.txt after-build-errors.txt
