#!/bin/sh
#
# make allmodconfig # or whatever
# test-build-patches

set -ex

rm -rf old-build.txt
rm -rf new-build.txt

parent=$1

if [ -z "$parent" ]; then
	parent=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
fi

make allmodconfig
./scripts/config --file .config -d werror
git rebase --exec \
	'git show | grep -q "not-for-review\|only-internal-review" || sudo make -j80' \
	$parent

echo "Test build patches succeeded"
